---

- name: Make cotainerd config directory
  file: 
    path: /etc/containerd
    state: directory

- name: Make kata config directory
  file: 
    path: /etc/kata-containers
    state: directory

- name: check if config is present
  stat:
    path: /etc/kata-containers/config.toml
  register: config_present

- name: Copy default configuration to /etc
  command: |
    cp /usr/share/defaults/kata-containers/configuration.toml /etc/kata-containers/config.toml
  when: config_present.stat.exists == False

- name: Configure containerd to use kata-runtime
  copy:
    dest: /etc/containerd/config.toml
    content: |
      [plugins.cri.containerd.runtimes.kata]
        runtime_type = "io.containerd.kata.v2"
        [plugins.cri.containerd.runtimes.kata.options]
          ConfigPath = "/etc/kata-containers/config.toml"

- name: Restarting containerd
  service:
    name: containerd
    enabled: yes
    state: restarted