---

- name: Make cotainerd config directory
  file: 
    path: /etc/containerd
    state: directory

- name: Make kata config directory
  file: 
    path: /etc/kata-containers
    state: directory

- name: Copy default configuration to /etc
  synchronize:
    src: /usr/share/defaults/kata-containers
    dest: /etc/kata-containers

- name: Configure containerd to use kata-runtime
  copy:
    dest: /etc/containerd/config.toml
    content: |
      [plugins.cri.containerd.runtimes.kata]
        runtime_type = "io.containerd.kata.v2"
        [plugins.cri.containerd.runtimes.kata.options]
          ConfigPath = "/etc/kata-containers/configuration.toml"

- name: Restarting containerd
  service:
    name: containerd
    enabled: yes
    state: restarted