---
- name: Update and upgrade all servers, set time 
  hosts: all
  roles: 
    - update_upgrade
    - timezone

- name: Disable Swap for kubernetes
  hosts: all
  roles:
    - disable_swap 

- name: Repair shitty ansible file that is broke because it sucks
  hosts: k8smaster
  roles:
    - repair_shitty_ansible_file

- name: Install Kata Containers
  hosts: k8sworker
  roles:
    - install_kata





