---
- name: Update all packages
  apt:
    state: latest
    upgrade: dist
    update_cache: yes

- name: Check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_check_result

- name: Set fact reboot check to false
  set_fact:
    reboot_check_result: false
  when: not reboot_check_result.stat.exists

- name: set fact reboot check to true
  set_fact:
    reboot_check_result: true
  when: reboot_check_result.stat.exists

- name: server update reboot | restart server
  reboot:
  when: reboot_check_result | bool