--- 

- name: Disable SWAP since kubernetes dosnt want swap enabled (1/2)
  shell: |
    swapoff -a



- name: Disable SWAP in fstab since kubernetes dosnt want swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

